export const doctors = [
  {
    id: 1,
    name: 'Dr. Arun Menon',
    specialization: 'Orthopedic',
    experience: '12 years',
    rating: 4.8,
    availableSlots: ['9:00 AM', '11:00 AM', '2:00 PM', '4:00 PM'],
    about: 'Specialist in bone and joint disorders with extensive surgical experience.',
  },
  {
    id: 2,
    name: 'Dr. Priya Sharma',
    specialization: 'Dentist (BDS)',
    experience: '8 years',
    rating: 4.6,
    availableSlots: ['10:00 AM', '12:00 PM', '3:00 PM'],
    about: 'Expert in dental care, cosmetic dentistry and oral surgery.',
  },
  {
    id: 3,
    name: 'Dr. Rahul Verma',
    specialization: 'Cardiologist',
    experience: '15 years',
    rating: 4.9,
    availableSlots: ['9:30 AM', '11:30 AM', '3:30 PM'],
    about: 'Senior cardiologist specializing in heart disease prevention and treatment.',
  },
  {
    id: 4,
    name: 'Dr. Sneha Pillai',
    specialization: 'Dermatologist',
    experience: '6 years',
    rating: 4.7,
    availableSlots: ['10:30 AM', '1:00 PM', '4:30 PM'],
    about: 'Specialist in skin conditions, acne treatment and cosmetic dermatology.',
  },
  {
    id: 5,
    name: 'Dr. Vikram Nair',
    specialization: 'General Physician',
    experience: '10 years',
    rating: 4.5,
    availableSlots: ['8:00 AM', '10:00 AM', '12:00 PM', '3:00 PM'],
    about: 'Experienced general physician handling all common illnesses and health checkups.',
  },
  {
    id: 6,
    name: 'Dr. Ananya Das',
    specialization: 'Neurologist',
    experience: '11 years',
    rating: 4.8,
    availableSlots: ['9:00 AM', '12:30 PM', '3:00 PM'],
    about: 'Specialist in brain and nervous system disorders including migraines and epilepsy.',
  },
]

export const patients = [
  {
    id: 1,
    name: 'Rahul Sharma',
    age: 34,
    condition: 'Knee Pain',
    appointmentDate: '2026-06-20',
    appointmentTime: '10:00 AM',
    appointmentDoctor: 'Dr. Arun Menon',
    medicines: ['Ibuprofen 400mg', 'Calcium Supplement'],
    diet: 'Avoid fried food, take warm water',
    prescription: null,
  },
  {
    id: 2,
    name: 'Priya Nair',
    age: 28,
    condition: 'Tooth Cavity',
    appointmentDate: '2026-06-21',
    appointmentTime: '11:30 AM',
    appointmentDoctor: 'Dr. Priya Sharma',
    medicines: ['Amoxicillin 500mg', 'Paracetamol 650mg'],
    diet: 'Avoid sweets, cold water',
    prescription: null,
  },
  {
    id: 3,
    name: 'Arun Kumar',
    age: 45,
    condition: 'Back Pain',
    appointmentDate: '2026-06-22',
    appointmentTime: '2:00 PM',
    appointmentDoctor: 'Dr. Rahul Verma',
    medicines: ['Diclofenac 50mg', 'Muscle Relaxant'],
    diet: 'Light stretching, avoid heavy lifting',
    prescription: null,
  },
]

export const appointments = []

export const pharmacistOrders = []